import { defineDirection, defineLens } from "konte";

export default defineDirection({
  brief: {
    logline: "A cook and a rival settle who burnt breakfast.",
    hook: "Smoke already curling off the pan.",
    audience: "konte developers checking that the DSL still holds together.",
    tone: "Light and quick.",
    look: "Flat cel shading, warm kitchen light.",
    outOfScope: ["A cooking tutorial"],
    tolerances: ["Background lettering may render as glyphs."],
  },
  policy: {
    format: {
      fps: 24,
      size: {
        megapixels: 0.9,
        delivery: { width: 1920, height: 1080 },
      },
    },
    lang: "en-US",
    fonts: ["Inter", "Noto Sans JP"],
    speech: "free",
  },
  lenses: [
    defineLens({
      name: "two-act",
      payoff: "resolve",
      beats: [
        { role: "provoke", fn: "ground", maxShare: 0.8 },
        { role: "resolve", fn: "payoff" },
      ],
    }),
  ],
  characters: {
    cook: {
      name: "the cook",
      promptDepiction: "boy",
      description: "A boy of twelve in a white apron, hair tied back.",
      voice: { id: "cookVoice", description: "A bright, eager young voice." },
    },
    rival: {
      name: "the rival",
      promptDepiction: "woman",
      description: "A woman in a green cardigan with reading glasses.",
      voice: { id: "rivalVoice", description: "A dry, amused alto." },
    },
  },
  narrator: { id: "narratorVoice", description: "A warm, unhurried baritone." },
  props: {
    pan: { name: "the pan", description: "A dented iron frying pan." },
  },
  locations: {
    kitchen: {
      name: "the kitchen",
      description: "A small sunlit kitchen.",
      landmarks: {
        window: {
          name: "the window",
          promptDepiction: "window",
          description: "A square window over the sink.",
        },
        stove: {
          name: "the stove",
          promptDepiction: "stove",
          description: "A white four-burner stove.",
        },
        table: {
          name: "the table",
          promptDepiction: "table",
          description: "A round pine table.",
        },
      },
    },
    yard: {
      name: "the yard",
      description: "A back yard behind the kitchen.",
      landmarks: {
        gate: { name: "the gate", promptDepiction: "gate", description: "A blue wooden gate." },
        tree: { name: "the tree", promptDepiction: "tree", description: "An old apple tree." },
      },
    },
  },
  setups: {
    kitchenWide: {
      name: "the kitchen, wide",
      description: "From the doorway at eye level.",
      location: "kitchen",
      framing: "wide",
      holds: ["window", "stove", "table"],
      within: null,
    },
    kitchenMedium: {
      name: "the kitchen, medium",
      description: "In on the stove and the table.",
      location: "kitchen",
      framing: "medium",
      holds: ["stove", "table"],
      within: "kitchenWide",
    },
    kitchenClose: {
      name: "the kitchen, close",
      description: "Over the table top.",
      location: "kitchen",
      framing: "close",
      holds: ["table"],
      within: "kitchenMedium",
    },
    panInsert: {
      name: "the pan, insert",
      description: "The pan filling the frame.",
      location: "kitchen",
      framing: "insert",
      holds: [],
    },
    yardWide: {
      name: "the yard, wide",
      description: "From the back step.",
      location: "yard",
      framing: "wide",
      holds: ["gate", "tree"],
    },
  },
  sequence: {
    lens: "two-act",
    pleasure: "funny",
    sequences: [
      {
        id: "act1",
        role: "provoke",
        synopsis: "Breakfast burns and the rival notices.",
        lens: "mini-drama",
        pleasure: "funny",
        shots: [
          {
            id: "01",
            role: "ordinary",
            action: "The cook flips eggs at the stove.",
            setup: "kitchenWide",
            duration: 3,
            lineup: ["cook"],
            telop: ["Morning."],
            script: [{ character: "cook", text: "Almost ready.", acting: "Humming, pleased." }],
          },
          {
            id: "02",
            role: "disruption",
            action: "The rival walks in and sniffs the air.",
            setup: "kitchenWide",
            join: "continuous",
            duration: 4,
            lineup: ["cook"],
            lineupTo: ["rival", "cook"],
            script: [{ character: "rival", text: "Something is burning." }],
          },
          {
            id: "03",
            role: "pressure",
            action: "Smoke rises off the pan and the neighbours shout.",
            setup: "kitchenMedium",
            duration: 2,
            lineup: ["rival", "cook"],
            script: [{ speaker: "neighbours", text: "Fire!" }],
            cutin: { setup: "panInsert", lineup: [] },
          },
          {
            kind: "aside",
            id: "eyecatch",
            label: "Eyecatch",
            duration: 2,
            telop: ["KITCHEN SINK"],
          },
          {
            kind: "graphic",
            id: "04",
            role: "pressure",
            action: "A recipe card fills the screen.",
            duration: 2,
            script: [{ narration: "Step one: watch the pan." }],
            cutin: { setup: "kitchenClose", lineup: ["cook"] },
          },
          {
            id: "05",
            role: "hero",
            action: "The cook plates the eggs, triumphant.",
            setup: "kitchenClose",
            join: "jump-forward",
            duration: 3,
            lineup: ["cook"],
          },
        ],
      },
      {
        id: "act2",
        role: "resolve",
        synopsis: "It turns out the rival burnt the toast last week.",
        lens: "comedy",
        pleasure: "funny",
        shots: [
          {
            id: "06",
            role: "setup",
            action: "Last week, the rival burns toast in the yard.",
            setup: "yardWide",
            join: "jump-back",
            duration: 3,
            lineup: ["rival"],
          },
          {
            id: "07",
            role: "violation",
            action: "The cook catches her at it.",
            setup: "yardWide",
            join: "continuous",
            duration: 3,
            lineup: ["rival"],
            lineupTo: ["cook", "rival"],
          },
          {
            id: "08",
            role: "button",
            action: "Back in the kitchen, the rival hands the cook a fresh pan.",
            setup: "kitchenMedium",
            join: "jump-forward",
            duration: 3,
            lineup: ["rival", "cook"],
          },
        ],
      },
    ],
  },
});
