import * as fs from "node:fs/promises";
import * as path from "node:path";
import { writeFileAtomic } from "./atomic-write.js";
import type { KonteState } from "./types/index.js";
import { ASSET_STAGES, variantDir } from "./variant-dir.js";
import { isProtectedVariant } from "./variant-lineage.js";

const ASSETS_PREFIX = `assets${path.sep}`;

export function assetsGitignorePath(videoRoot: string): string {
  return path.join(videoRoot, "assets", ".gitignore");
}

export interface AssetsGitTracking {
  // Variant directories git tracks, relative to the video root.
  keptDirs: ReadonlySet<string>;
  // Whether `assets/.gitignore` keeps a variant's file from git.
  ignores(file: string): boolean;
}

/**
 * What `assets/.gitignore` lets git track: the variant directories holding a protected variant's file.
 * Judged by directory because a patched variant's file lives in its chain's returned step (see
 * `variantsHostedBy`). A directory no state variant owns stays ignored.
 */
export function assetsGitTracking(state: KonteState): AssetsGitTracking {
  const variantDirs = new Set<string>();
  for (const [address, asset] of Object.entries(state.assets)) {
    for (const variantId of Object.keys(asset.variants ?? {})) {
      variantDirs.add(variantDir("", address, variantId));
    }
  }
  const holdingDir = (file: string): string | null => {
    for (let dir = path.dirname(path.join(file)); dir.startsWith(ASSETS_PREFIX); ) {
      if (variantDirs.has(dir)) return dir;
      dir = path.dirname(dir);
    }
    return null;
  };

  const keptDirs = new Set<string>();
  for (const [address, asset] of Object.entries(state.assets)) {
    for (const [variantId, variant] of Object.entries(asset.variants ?? {})) {
      if (!variant.file || !isProtectedVariant(state, address, variantId)) continue;
      const dir = holdingDir(variant.file);
      if (dir) keptDirs.add(dir);
    }
  }

  return {
    keptDirs,
    ignores: (file) => {
      const dir = holdingDir(file);
      return dir !== null && !keptDirs.has(dir);
    },
  };
}

export function renderAssetsGitignore(state: KonteState): string {
  const lines = ["# generated by konte from konte.state.json — do not edit"];
  for (const stage of ASSET_STAGES) {
    lines.push(`/${stage}/*/v-*/`, `!/${stage}/patch/v-*/`, `/${stage}/patch/v-*/*/v-*/`);
  }
  const kept = [...assetsGitTracking(state).keptDirs].map((dir) =>
    dir.slice(ASSETS_PREFIX.length).split(path.sep).join("/"),
  );
  for (const dir of kept.sort()) lines.push(`!/${dir}/`);
  return `${lines.join("\n")}\n`;
}

export async function readAssetsGitignore(videoRoot: string): Promise<string | null> {
  try {
    return await fs.readFile(assetsGitignorePath(videoRoot), "utf-8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
}

export async function syncAssetsGitignore(videoRoot: string, state: KonteState): Promise<void> {
  const content = renderAssetsGitignore(state);
  if ((await readAssetsGitignore(videoRoot)) === content) return;
  await writeFileAtomic(assetsGitignorePath(videoRoot), content);
}
