import { isMaterializedLeafAssetPath } from "./address.js";
import type { DependencyGraph } from "./graph.js";

interface DependencyLevels {
  levels: readonly (readonly string[])[];
  levelOf: ReadonlyMap<string, number>;
}

// Composition and stem nodes live in the dependency graph for staleness propagation, but
// they are materialized locally — not generated by a backend — so they are not part of
// the generation waves this computes. Skip them.
export function computeDependencyLevels(graph: DependencyGraph): DependencyLevels {
  const levelOf = new Map<string, number>();

  for (const node of graph.topologicalOrder) {
    if (isMaterializedLeafAssetPath(node)) continue;
    const deps = graph.dependencies.get(node) ?? [];
    let maxDepLevel = -1;
    for (const dep of deps) {
      const depLevel = levelOf.get(dep) ?? 0;
      if (depLevel > maxDepLevel) {
        maxDepLevel = depLevel;
      }
    }
    levelOf.set(node, maxDepLevel + 1);
  }

  const maxLevel = Math.max(-1, ...levelOf.values());
  const buckets: string[][] = [];
  for (let i = 0; i <= maxLevel; i++) {
    buckets.push([]);
  }

  for (const node of graph.topologicalOrder) {
    const level = levelOf.get(node);
    if (level === undefined) continue;
    buckets[level]!.push(node);
  }

  return { levels: buckets, levelOf };
}
