import {
  type Stage,
  formatAssetPathSuffix,
  isPatchAddress,
  isPlateAddress,
  parseAddress,
} from "./address.js";
import { JobIndex } from "./job-index.js";
import { describePendingJob } from "./pending-jobs.js";
import {
  type PatchHashes,
  type StalenessCache,
  collectStaleUnacceptedVariants,
  collectStaleVariants,
  computeVariantStaleness,
  formatStaleCause,
  formatStaleReason,
  isVariantStale,
  undecidedTakeBesideAccepted,
  variantsNewestFirst,
} from "./staleness.js";
import { ERROR_GLIMPSE_WIDTH, truncateSingleLine } from "./truncate.js";
import type { AssetDefinition, ExportJob, JobRecord, KonteState } from "./types/index.js";
import { collectDescendants, isReviewLeaf } from "./variant-lineage.js";

// "composition" is a synthetic kind: a shot's assembled output, not a real
// AssetDefinition. It is reviewable but never generated by a backend.
type AddressKind = AssetDefinition["kind"] | "composition" | "stem" | "animatic";

export interface AddressInfo {
  address: string;
  assetKind: AddressKind | null;
  /**
   * A human ever decides about this address. False for an intermediate — an asset a stage declared
   * without returning it: generated and tracked like any other, but read through the asset that
   * consumes it, so it is on no review surface and nothing waits on an accept of it. It counts
   * toward neither the accept nor the generation ratio; only a `file` one's presence on disk shows,
   * since putting the file there is the author's work whoever reads it. Also false for a plate,
   * judged inside the panels drawn on it; it is still `generate` work.
   */
  reviewTarget: boolean;
  /**
   * This address needs a verdict, but no review surface lands one on it — a konte bug, not the
   * author's. Set by the caller, which knows what each stage's review can decide
   * (`videoReviewDecidableAddresses`). Such an address is reported under "Problems" rather than
   * "Needs review": sending a reviewer to a page that will not show it is what let the two bugs
   * this flag exists to catch sit in a status report indefinitely.
   */
  reviewUnreachable: boolean;
  hasAccepted: boolean;
  /** Has at least one variant that produced an output file (accepted, stale, or awaiting review). */
  hasOutputFile: boolean;
  /**
   * The asset is accepted, but this ready, non-stale variant stands undecided beside it — a take
   * (e.g. from `reroll`) awaiting a verdict. Null when there is none, including when every rival
   * was dismissed. The newest such take, which is not necessarily newer than the accepted one.
   * Mirrors the preview UI's `hasNewerReadyVariant`.
   */
  undecidedTakeVariantId: string | null;
  /**
   * The accepted take has this undecided patch output hanging off it; null when it has none.
   * Tracked apart from `undecidedTakeVariantId` for its wording alone: the reviewer's question is
   * whether the fix landed, not whether an alternative is better. `sourceVariantId` is the take it
   * corrects — the id `konte patch remove` takes, and `hasScript` whether that script is still there.
   */
  patchedAwaitingReview: {
    variantId: string;
    sourceVariantId: string;
    hasScript: boolean;
  } | null;
  /** The takes `readyCount` counts, in canonical resolution order — `readyVariantIds[0]` is the
   * take `selectResolvedVariant` resolves to while nothing here is accepted. */
  readyVariantIds: string[];
  readyCount: number;
  /**
   * A materialized leaf (composition / stem) is ready to be reviewed now: renderable structure and
   * every ref resolves. Leaves are materialized only on accept, so a never-accepted leaf has no
   * variant — its first-review need is this live signal, not `readyCount`. False for non-leaves.
   */
  leafReadyForReview: boolean;
  generatingJobs: { variantId: string; status: "running" | "queued"; progress: number | null }[];
  blockedJobs: {
    variantId: string;
    waitingOn: string[];
  }[];
  failedJobs: { variantId: string; error: string | null }[];
  staleVariants: {
    variantId: string;
    inputStale: boolean;
    definitionStale: boolean;
    patchStale: boolean;
    changedInputs: { assetPath: string; recorded: string; current: string | null }[];
  }[];
  /**
   * Stale takes nobody accepted, newest-first. Reported apart from `staleVariants` because the fix
   * differs: an accepted stale take is refreshed by a `reroll` a human asks for, while these are
   * ungenerated work the next `generate` replaces. See `needsRegeneration`.
   */
  staleUnacceptedVariants: {
    variantId: string;
    inputStale: boolean;
    definitionStale: boolean;
    patchStale: boolean;
    changedInputs: { assetPath: string; recorded: string; current: string | null }[];
  }[];
  /**
   * The accepted take is stale, yet the accept stands: it holds a human verdict (a generation or
   * patch output) and only its inputs have moved, or every video take built on it holds one (set by
   * `buildStatusReport`, which has the graph). No section, count or step names it.
   */
  staleAcceptStands: boolean;
  problemVariants: string[];
  /**
   * Takes the reviewer decided against (`status === "dismissed"`), whatever their staleness. They
   * are neither review candidates nor resolvable, so an address holding nothing else is work for
   * `generate` — see `needsRegeneration`.
   */
  dismissedCount: number;
  /**
   * A `file` asset's declared path when the media is not on disk. It is the whole of the fix (put
   * the file there), and a `file` asset has no variant for any other section to surface, so this is
   * what puts it under "Problems". Null for a present file and for every other kind.
   */
  missingFilePath: string | null;
}

export interface StatusSection {
  title: string;
  items: {
    address: string;
    detail: string;
    /**
     * The take the item is about — set on "Needs review". Absent on a materialized leaf, which has
     * no variant until it is accepted, and on items that are about an address.
     */
    variantId?: string;
  }[];
}

export interface ExportReadiness {
  label: string;
  /** Generation assets only — `file` assets have no accept lifecycle and are reported separately. */
  total: number;
  accepted: number;
  missing: string[];
  /** Generation assets that produced at least one output file (whether accepted or awaiting review). */
  generated: number;
  /**
   * Generation assets with no output file and no job in flight — the exact set a `generate` would
   * act on. An asset whose job is running/queued/pending is excluded (it counts in `inFlight`):
   * listing it here would read as "never generated" and invite a redundant `generate`.
   */
  notGenerated: string[];
  /**
   * Generation assets that HAVE output, but only stale unaccepted takes — `generate` acts on these
   * too, so Next steps must offer it. Kept apart from `notGenerated`, which means no output at all.
   */
  needsRegenerate: string[];
  /** Generation assets with a running, queued, or pending job — already handled; do not generate. */
  inFlight: number;
  /**
   * Accepted-but-stale assets with no fresher take yet — the refresh is a `reroll`.
   */
  staleAwaitingReroll: string[];
  /**
   * Accepted-but-stale assets whose reroll has already landed a fresh, non-stale take
   * awaiting review — the refresh is `accept`, not another `reroll`.
   */
  staleAwaitingAccept: string[];
  /** File assets present on disk. They're never "accepted" (no review) — just ready. */
  filesReady: number;
  /** File assets declared but not found on disk (e.g. a bad path) — a real problem. */
  filesMissing: string[];
  /**
   * Undeveloped shots in this stage (a `pendingShot`, the same form in either stage) — they carry
   * no address so they never appear in the accept counts. Export refuses while a VIDEO one remains;
   * an animatic one only holds the board back.
   * Seeded by computeExportReadiness from its `pendingShotsByStage` argument (0 when unset).
   */
  pendingShots: number;
  /**
   * Reference asset ids of this stage's unaccepted cast — character looks and voice samples, the
   * gate that blocks animatic/video generation. Populated by the status builder (which has the
   * direction); computeExportReadiness leaves it empty.
   */
  unacceptedCast: string[];
  /**
   * The video's delivery needs an upscaler that video.tsx does not wire — export refuses with
   * DELIVERY_UPSCALE_REQUIRED. Populated by the status builder (which has the video definition);
   * computeExportReadiness leaves it false.
   */
  deliveryUpscalerMissing: boolean;
  /**
   * Of this stage's generate work (`notGenerated` and `needsRegenerate` alike), what the animatic
   * gate withholds: `generate` skips these, so the step is an accept, not another generate — and
   * when it covers the whole work list, `generate` is not a step at all. Populated by the status
   * builder (which computes the gate); computeExportReadiness leaves it empty.
   */
}

interface OrphanInfo {
  orphanJobs: { variantId: string; address: string; jobStatus: string }[];
}

export interface LastExport {
  label: string;
  noDelivery: boolean;
  outputFile: string;
  completedAt: string | null;
  // The export's stamped signature no longer matches the current definition — a render fn,
  // soundtrack, or delivery config changed since, so the delivered file is out of date and a
  // re-export is needed (see computeExportSignature). False when the signature matches, or can't be
  // checked (no current signature, or a legacy job with none stamped).
  outOfDate: boolean;
}

// The most recent successful video export, so status can report the delivered artifact instead of
// leaving "ready to export" the only signal after an export already succeeded. Export jobs only ever
// belong to the video stage; returns nothing when no video address is in `addresses` so a narrowed
// status view doesn't surface an unrelated export.
export function computeLastExports(
  // Whether the video stage is in scope — an export belongs to the video stage, so with the video
  // out of scope there is nothing to report. Derived from the loaded video definition (status) or
  // from the presence of video assets in state (probe export), not guessed from an address list.
  videoInScope: boolean,
  jobs: JobRecord[],
  // The current export signature (see computeExportSignature), used to flag a last export whose
  // soundtrack/delivery config has since changed. Omitted when no video definition is in scope; no
  // current signature leaves the export not flagged.
  currentSignature?: () => string | null,
): LastExport[] {
  if (!videoInScope) return [];

  let latest: ExportJob | null = null;
  for (const job of jobs) {
    if (job.kind !== "export" || job.status !== "completed" || !job.outputFile) continue;
    // completedAt is an ISO 8601 UTC string, so a lexical compare orders chronologically.
    if (!latest || (job.completedAt ?? "") > (latest.completedAt ?? "")) {
      latest = job;
    }
  }
  if (!latest) return [];

  const current = currentSignature?.() ?? null;
  return [
    {
      label: "video",
      noDelivery: latest.noDelivery,
      outputFile: latest.outputFile as string,
      completedAt: latest.completedAt,
      // Only flag when both signatures are known and differ — a missing current or stamped
      // signature means "can't tell", which must not masquerade as a confident "up to date".
      outOfDate:
        latest.exportSignature != null && current != null && latest.exportSignature !== current,
    },
  ];
}

export function buildAddressInfo(
  address: string,
  state: KonteState,
  jobsByVariantId: Map<string, JobRecord>,
  assetKind: AddressKind | null,
  currentDefinitionHash: string | null = null,
  jobs: JobIndex = new JobIndex(),
  // A file asset has no generate/review/accept lifecycle — its "acceptance" is just the
  // file being present on disk. The caller resolves that (it needs fs access) and forces
  // accepted here, so a declared-and-present file reads as complete before any sync.
  forceAccepted = false,
  // Dead composition leftover variant ids for this address (from collectDeadCompositionVariants)
  // — never counted as "ready". A composition is auto-materialized, not rerolled, so a variant
  // that isn't the live one (the current definition can't materialize it, or it predates the
  // current definition/inputs) is a stale leftover that must not surface as "N ready". Empty for
  // non-compositions, so this is a no-op there.
  deadVariantIds: ReadonlySet<string> = new Set(),
  // A composition/stem leaf is ready to review (renderable, refs resolvable) — the caller computes
  // it from the live definition (it needs the video definition + manager). False for non-leaves.
  leafReadyForReview = false,
  // The declared path of a `file` asset whose media is absent — the caller resolves it (it needs
  // fs access and the definition). Null for a present file and every other kind.
  missingFilePath: string | null = null,
  // Current patch-definition hash per source variant id, when the caller has loaded the patch
  // scripts. Lets an edited patch's old output read as stale here too.
  patchHashes?: PatchHashes,
  // Shared staleness memo for a read-only sweep — the four staleness passes below re-walk the
  // same upstream cones per variant otherwise. The caller owns its lifetime (drop on any write).
  stalenessCache?: StalenessCache,
  // Whether anyone reviews this address at all (see AddressInfo.reviewTarget). The caller decides
  // it — it needs the definition — and only a reference intermediate is not one.
  reviewTarget = true,
  // See AddressInfo.reviewUnreachable. The caller decides it; false leaves the address on the
  // ordinary review path.
  reviewUnreachable = false,
  // Whether the address's asset is deterministic — its stale accept is re-baked, never kept.
  deterministic = false,
): AddressInfo {
  const target = state.assets[address];
  const variants = Object.entries(target?.variants ?? {});

  const hasAccepted = forceAccepted || variants.some(([, v]) => v.status === "accepted");
  const hasOutputFile = variants.some(([, v]) => !!v.file);
  const undecidedTakeVariantId = undecidedTakeBesideAccepted(
    state,
    address,
    currentDefinitionHash,
    deadVariantIds,
    patchHashes,
    stalenessCache,
  );
  // Only lineage leaves count. A take that has been patched is not one of the choices any more —
  // it is the "before" of the variant that replaced it — so counting it would report two things to
  // review where the reviewer sees one.
  // Ordered by `variantsNewestFirst`, the comparator canonical resolution uses, so the first entry
  // is the take `selectResolvedVariant` hands to preview and render. A different order here would
  // send a reviewer to judge one take and an accept to a different one.
  const readyVariantIds = variantsNewestFirst(Object.fromEntries(variants))
    .filter(([variantId, v]) => {
      if (!v.file || deadVariantIds.has(variantId)) return false;
      // A take decided against is settled work: counting one would keep an address in
      // "Needs review" after the reviewer said no to everything at it.
      if (v.status === "dismissed") return false;
      if (!isReviewLeaf(state, address, variantId)) return false;
      const staleness = computeVariantStaleness(
        state,
        address,
        v,
        currentDefinitionHash,
        patchHashes,
        stalenessCache,
      );
      // Stale on either axis is work to redo, not a take to review: `generate` replaces exactly
      // these (`assetSkipReason`), so counting one here would send a reviewer to judge a picture the
      // next run throws away — and an accept made there would then protect it. They are reported
      // instead under "Needs regenerate", or, for a since-edited patch script, "Pending patches".
      return !staleness.inputStale && !staleness.definitionStale;
    })
    .map(([variantId]) => variantId);
  const readyCount = readyVariantIds.length;
  // An accepted take with an undecided correction hanging off it. Reported apart from
  // `undecidedTakeVariantId` for its wording alone — the reviewer's question is "did the fix land?",
  // not "is this alternative better?". It clears the same three ways any rival does: accept it,
  // dismiss it (by accepting the original beside it), or `konte patch remove`.
  const patchedAwaitingReviewVariantId =
    variants
      .filter(([, v]) => v.status === "accepted")
      .flatMap(([variantId]) => collectDescendants(state, address, variantId))
      .find((id) => {
        const child = target?.variants?.[id];
        if (child?.file == null || child.status !== "none") return false;
        if (!isReviewLeaf(state, address, id) || deadVariantIds.has(id)) return false;
        if (
          !isVariantStale(state, address, child, currentDefinitionHash, patchHashes, stalenessCache)
        ) {
          return true;
        }
        // A stale correction is not review work: an accept beside it cannot dismiss it
        // (`readyUndecidedTakes` skips a stale take), so the item would stand whatever the reviewer
        // decided. Its live script owns it under "Pending patches" — with no script left there is
        // no other owner, so it stays here, routed to `prune`.
        return (
          patchHashes != null && child.derivedFrom != null && !patchHashes.has(child.derivedFrom)
        );
      }) ?? null;
  const patchedAwaitingReviewSource =
    patchedAwaitingReviewVariantId != null
      ? (target?.variants?.[patchedAwaitingReviewVariantId]?.derivedFrom ?? null)
      : null;
  const patchedAwaitingReview =
    patchedAwaitingReviewVariantId != null && patchedAwaitingReviewSource != null
      ? {
          variantId: patchedAwaitingReviewVariantId,
          sourceVariantId: patchedAwaitingReviewSource,
          hasScript: patchHashes == null || patchHashes.has(patchedAwaitingReviewSource),
        }
      : null;

  const generatingJobs: AddressInfo["generatingJobs"] = [];
  const blockedJobs: AddressInfo["blockedJobs"] = [];
  const failedJobs: AddressInfo["failedJobs"] = [];
  const problemVariants: string[] = [];

  for (const [variantId, v] of variants) {
    const job = jobsByVariantId.get(variantId);
    if (job && (job.status === "running" || job.status === "queued")) {
      generatingJobs.push({ variantId, status: job.status, progress: job.progress });
    } else if (job && job.kind === "generation" && job.status === "pending") {
      const reason = describePendingJob(job, state, jobs, stalenessCache);
      blockedJobs.push({ variantId, waitingOn: reason.submittable ? [] : reason.waitingOn });
    } else if (job && job.status === "failed") {
      failedJobs.push({ variantId, error: job.error });
    } else if (!v.file && !v.metadata?.error && !v.metadata?.cancelledAt) {
      const hasActiveJob =
        job && (job.status === "running" || job.status === "queued" || job.status === "pending");
      if (!hasActiveJob) {
        problemVariants.push(variantId);
      }
    }
  }

  const staleVariants = collectStaleVariants(
    state,
    address,
    currentDefinitionHash,
    patchHashes,
    stalenessCache,
  );
  const staleUnacceptedVariants = collectStaleUnacceptedVariants(
    state,
    address,
    currentDefinitionHash,
    patchHashes,
    stalenessCache,
  );
  const dismissedCount = variants.filter(
    ([variantId, v]) => v.status === "dismissed" && !deadVariantIds.has(variantId),
  ).length;
  const staleAcceptStands =
    assetKind !== "composition" &&
    assetKind !== "stem" &&
    assetKind !== "animatic" &&
    staleVariants.some(
      (sv) =>
        sv.inputStale &&
        !sv.definitionStale &&
        (!deterministic || target?.variants?.[sv.variantId]?.derivedFrom != null),
    );

  return {
    address,
    assetKind,
    reviewTarget,
    reviewUnreachable,
    hasAccepted,
    hasOutputFile,
    undecidedTakeVariantId,
    patchedAwaitingReview,
    readyVariantIds,
    readyCount,
    leafReadyForReview,
    generatingJobs,
    blockedJobs,
    failedJobs,
    staleVariants,
    staleUnacceptedVariants,
    staleAcceptStands,
    problemVariants,
    dismissedCount,
    missingFilePath,
  };
}

/**
 * The address holds output, but nothing of it is both usable and undecided — every take is stale or
 * dismissed, and none was accepted — so the next `generate` will replace them all. Exactly
 * `assetSkipReason`'s "generate must act here" verdict, expressed over an AddressInfo.
 *
 * `readyCount === 0` is what keeps this disjoint from "Needs review" — the two read the same
 * staleness, so an address is a review candidate or regeneration work, never both.
 */
function needsRegeneration(info: AddressInfo): boolean {
  if (!isGenerationAsset(info.assetKind)) return false;
  if (isPatchAddress(info.address)) return false;
  if (info.hasAccepted || info.readyCount > 0) return false;
  if (info.staleUnacceptedVariants.length === 0 && info.dismissedCount === 0) return false;
  // "Problems" claims the address on the same guard (unaccepted, nothing ready) and names a
  // different fix — `clean` a dead take, read a job's error. One address, one instruction.
  if (info.problemVariants.length > 0 || info.failedJobs.length > 0) return false;
  // Already being replaced — naming it would invite a second, redundant `generate`.
  return info.generatingJobs.length === 0 && info.blockedJobs.length === 0;
}

function isGenerationAsset(kind: AddressKind | null): boolean {
  return kind !== null && kind !== "file" && kind !== "composition" && kind !== "stem";
}

// A one-line peek of a job error, shown inline next to a failure. The full text
// is available via `konte inspect <address>`.
function formatErrorGlimpse(error: string | null): string {
  if (!error) return "";
  const peek = truncateSingleLine(error, ERROR_GLIMPSE_WIDTH);
  return peek ? `: ${peek}` : "";
}

// The "Problems" section's real-asset rule, shared with `konte reroll --failed`: every take at the
// address is dead or failed and there is nothing accepted or ready to fall back on. Orphan jobs and
// model-download failures are reported beside it but have no state variant, so they are not here.
export function isProblemAddress(info: AddressInfo): boolean {
  return (
    !info.hasAccepted &&
    info.readyCount === 0 &&
    (info.problemVariants.length > 0 || info.failedJobs.length > 0)
  );
}

export function detectOrphans(state: KonteState, allJobs: JobRecord[]): OrphanInfo {
  const stateVariantIds = new Set<string>();
  for (const assetState of Object.values(state.assets)) {
    for (const variantId of Object.keys(assetState.variants ?? {})) {
      stateVariantIds.add(variantId);
    }
  }

  const orphanJobs: OrphanInfo["orphanJobs"] = [];
  for (const job of allJobs) {
    // Model-download jobs aren't tied to an asset variant, so they're never orphans.
    if (job.kind !== "generation") continue;
    if (job.status === "completed" || job.status === "failed" || job.status === "cancelled")
      continue;
    if (!stateVariantIds.has(job.variantId)) {
      orphanJobs.push({ variantId: job.variantId, address: job.address, jobStatus: job.status });
    }
  }

  return { orphanJobs };
}

export function computeStatusSections(
  infos: AddressInfo[],
  orphans?: OrphanInfo,
  // Standalone failed jobs not tied to an asset variant — comfy model downloads and
  // custom node install/activate jobs. They block the generation jobs that depend on
  // them, so surface them by their own label (e.g. the model filename or node id). `what`
  // names the kind of job for the detail line (defaults to "model download").
  failedJobs?: { jobId: string; label: string; error: string | null; what?: string }[],
): StatusSection[] {
  const sections: StatusSection[] = [];

  // Everything whose next step is "open the review UI and accept" — a first review, a fresh take
  // beside an accepted one, or an accepted leaf whose upstream moved. They are one section because
  // they are one action (`konte preview <stage>`, then accept); "Stale" and "Problems" stay separate
  // because theirs differ (reroll, clean). The per-item detail says which case it is.
  const needsReview: StatusSection["items"] = [];
  // The same rows, for an address no surface decides. Collected here rather than judged on the flag
  // alone: "needs a verdict but nothing offers one" is only true of an address that needs a verdict
  // now, so an ungenerated or already-settled one must not be reported as a bug.
  const unreachable: StatusSection["items"] = [];
  const unreachableAddresses = new Set(
    infos.filter((info) => info.reviewUnreachable).map((info) => info.address),
  );
  for (const info of infos) {
    // A patch chain's intermediate step is machinery, not a take: nothing waits on a decision
    // about it, because the step after it consumes whatever is currently ready. Its correction
    // asks for the review, at the source address. `inspect` still shows it, and `konte accept`
    // still pins one deliberately.
    if (isPatchAddress(info.address)) continue;
    // A reference intermediate is machinery in the same way: the asset that consumes it is what
    // gets reviewed, so naming it here would send a reviewer to a page that does not show it.
    if (!info.reviewTarget) continue;

    // A composition/stem leaf is materialized only on accept, so a never-accepted one has no
    // variant: its first-review need is the live `leafReadyForReview` signal (renderable, refs
    // resolvable), not `readyCount`. Both compositions and stems belong here — same "review and
    // accept" experience.
    const isLeaf =
      info.assetKind === "composition" ||
      info.assetKind === "stem" ||
      info.assetKind === "animatic";
    if (isLeaf) {
      if (info.leafReadyForReview && !info.hasAccepted) {
        needsReview.push({
          address: info.address,
          // The animatic says what accepting it does — it is the one review that releases a spend,
          // and a reviewer reading a list of addresses has no other way to know that.
          detail:
            info.assetKind === "stem"
              ? "audio mix"
              : info.assetKind === "animatic"
                ? "animatic — accept to release the shot's motion spend"
                : "",
        });
      }
      // An accepted leaf whose upstream changed is out of date. It cannot be rerolled — it is
      // re-rendered from the live definition — so its refresh is another review, not a regenerate.
      for (const sv of info.staleVariants) {
        needsReview.push({
          address: info.address,
          detail: `accepted take is ${formatStaleReason(sv)}`,
        });
      }
    } else if (isGenerationAsset(info.assetKind) && info.readyCount > 0 && !info.hasAccepted) {
      needsReview.push({
        address: info.address,
        detail: "",
        ...(info.readyVariantIds[0] ? { variantId: info.readyVariantIds[0] } : {}),
      });
    } else if (isGenerationAsset(info.assetKind) && info.patchedAwaitingReview) {
      // A correction of the accepted take is ready. Reported before the "newer take" branch and
      // on its own wording because the reviewer's question is different: not "is this alternative
      // better?" but "did the fix land?".
      needsReview.push({
        address: info.address,
        detail: info.patchedAwaitingReview.hasScript
          ? `patched — accept it, or konte patch remove ${info.patchedAwaitingReview.sourceVariantId} to drop the fix`
          : "patched — its patch script is gone; accept it, or konte prune to drop it",
        variantId: info.patchedAwaitingReview.variantId,
      });
    } else if (isGenerationAsset(info.assetKind) && info.undecidedTakeVariantId) {
      // Accepted, but a take (e.g. from `reroll`) stands undecided beside it — offer it for
      // re-review without forcing an unaccept. It is not necessarily newer than the accept, so the
      // wording claims no order. (Composition re-review is handled by its own staleness-based
      // section.)
      needsReview.push({
        address: info.address,
        detail: "undecided take beside the accept",
        variantId: info.undecidedTakeVariantId,
      });
    }
  }
  // Whatever the loop above decided this address needs, an unreachable one is not a review step —
  // naming it under "Needs review" sends a reviewer to a page that will not show it.
  for (let i = needsReview.length - 1; i >= 0; i--) {
    const item = needsReview[i]!;
    if (!unreachableAddresses.has(item.address)) continue;
    needsReview.splice(i, 1);
    unreachable.push(item);
  }
  if (needsReview.length > 0) {
    sections.push({ title: "Needs review", items: needsReview });
  }

  const problems: StatusSection["items"] = unreachable.map(({ address }) => ({
    address,
    detail: "needs a verdict but no review surface offers one — konte bug",
  }));
  for (const info of infos) {
    // A superseded address — one with an accepted or ready (non-input-stale) variant — has a
    // healthy resolved output, so its earlier dead variants (a failed job, or a no-file variant
    // left behind by a since-successful reroll) are no longer problems. Drop them so a rerolled-
    // and-accepted asset stops reporting "Problems" for a failure it already replaced.
    if (info.hasAccepted || info.readyCount > 0) continue;
    // A declared file that isn't there is broken in the same way a variant with no output is —
    // and unlike those, naming the path is the whole instruction.
    if (info.missingFilePath) {
      problems.push({ address: info.address, detail: `file not found: ${info.missingFilePath}` });
    }
    for (const variantId of info.problemVariants) {
      problems.push({
        address: info.address,
        detail: `${variantId} no file, no active job`,
      });
    }
    // A failed job is a problem too, but distinct from "never started" — say so
    // and peek at the error so the two aren't conflated.
    for (const job of info.failedJobs) {
      problems.push({
        address: info.address,
        detail: `${job.variantId} generation job failed${formatErrorGlimpse(job.error)}`,
      });
    }
  }
  if (orphans) {
    for (const oj of orphans.orphanJobs) {
      problems.push({
        address: oj.address,
        detail: `${oj.variantId} orphan job (${oj.jobStatus}), no variant in state`,
      });
    }
  }
  if (failedJobs) {
    for (const fj of failedJobs) {
      problems.push({
        address: fj.label,
        detail: `${fj.what ?? "model download"} job failed${formatErrorGlimpse(fj.error)}`,
      });
    }
  }
  if (problems.length > 0) {
    sections.push({ title: "Problems", items: problems });
  }

  // Ungenerated work that already has output: every take is stale or dismissed and none is
  // accepted, so the next `generate` replaces them.
  const needsRegenerate: StatusSection["items"] = [];
  for (const info of infos) {
    if (!needsRegeneration(info)) continue;
    const newest = info.staleUnacceptedVariants[0];
    if (newest) {
      needsRegenerate.push({ address: info.address, detail: formatStaleCause(newest) });
    } else if (info.dismissedCount > 0) {
      needsRegenerate.push({
        address: info.address,
        detail: `${info.dismissedCount} take(s) dismissed, none kept`,
      });
    }
  }
  if (needsRegenerate.length > 0) {
    sections.push({ title: "Needs regenerate", items: needsRegenerate });
  }

  // Generation assets only — a stale leaf's refresh is a re-review, so it sits in "Needs review".
  // collectStaleVariants returns accepted variants only, so "accepted" needs no saying here, and
  // `reroll` takes the address, never the variant id — `konte inspect <address>` has the variants.
  const stale: StatusSection["items"] = [];
  for (const info of infos) {
    if (
      info.assetKind === "composition" ||
      info.assetKind === "stem" ||
      info.assetKind === "animatic" ||
      info.staleAcceptStands
    ) {
      continue;
    }
    for (const sv of info.staleVariants) {
      stale.push({ address: info.address, detail: formatStaleCause(sv) });
    }
  }
  if (stale.length > 0) {
    sections.push({ title: "Stale", items: stale });
  }

  // Running/queued/pending jobs are deliberately absent: nothing to act on (the pipeline submits a
  // pending job once its deps land, and `konte job wait` is what blocks for the outcome), and
  // `konte job list` already reports them with more detail. Their only bearing on a decision here is that
  // `generate` must not be re-run for them — carried by the readiness line's in-flight count.
  return sections;
}

// Pipeline order: the shared pool (reference plates) feeds the board, which feeds the video, so the
// first unfinished line is the one to work on.
const STAGE_ORDER: string[] = ["reference", "animatic", "video"] satisfies Stage[];

export function computeExportReadiness(
  infos: AddressInfo[],
  pendingShotsByStage?: Partial<Record<Stage, number>>,
): ExportReadiness[] {
  type Acc = {
    total: number;
    accepted: number;
    missing: string[];
    generated: number;
    notGenerated: string[];
    needsRegenerate: string[];
    inFlight: number;
    staleAwaitingReroll: string[];
    staleAwaitingAccept: string[];
    filesReady: number;
    filesMissing: string[];
  };
  // One group per stage — an address is its asset path, so a stage has a single implicit instance.
  const stageMap = new Map<string, Acc>();

  const ensure = (m: Map<string, Acc>, key: string): Acc => {
    let e = m.get(key);
    if (!e) {
      e = {
        total: 0,
        accepted: 0,
        missing: [],
        generated: 0,
        notGenerated: [],
        needsRegenerate: [],
        inFlight: 0,
        staleAwaitingReroll: [],
        staleAwaitingAccept: [],
        filesReady: 0,
        filesMissing: [],
      };
      m.set(key, e);
    }
    return e;
  };
  const countGenerateWork = (entry: Acc, info: AddressInfo, suffix: string) => {
    if (info.hasOutputFile) {
      // Generated, but nothing there resolves any more — `generate` will replace it, so it belongs
      // in the work list even though the "generated" count already claimed it.
      if (needsRegeneration(info)) entry.needsRegenerate.push(suffix);
    } else if (info.generatingJobs.length > 0 || info.blockedJobs.length > 0) entry.inFlight++;
    else entry.notGenerated.push(suffix);
  };
  const accumulate = (entry: Acc, info: AddressInfo, suffix: string) => {
    // A file asset has no generate/review/accept lifecycle — it's complete once present on
    // disk (hasAccepted reflects that). Report it separately so it's never miscounted as a
    // reviewed-and-accepted generation asset.
    if (info.assetKind === "file") {
      if (info.hasAccepted) entry.filesReady++;
      else entry.filesMissing.push(suffix);
      return;
    }
    // An intermediate counts on neither axis: nobody accepts one, and `generate` reaches it through
    // the asset that consumes it. A `file` one is the exception handled above — putting the file on
    // disk is the author's work whoever reads it. A plate is the other: baked while every shot on
    // it may still be a `pendingShot`, it is `generate` work of its own.
    if (!info.reviewTarget) {
      if (isPlateAddress(info.address)) countGenerateWork(entry, info, suffix);
      return;
    }
    entry.total++;
    if (info.hasAccepted) {
      entry.accepted++;
      // An accepted variant that has gone stale (its inputs or definition changed) and whose
      // accept does not stand is not truly export-ready — surface it so a fully-accepted stage
      // isn't reported as ready to export. Route by whether a non-stale take is already awaiting
      // a verdict: if so the refresh is `accept`, otherwise it's `reroll`.
      if (info.staleVariants.length > 0 && !info.staleAcceptStands) {
        if (info.undecidedTakeVariantId !== null) entry.staleAwaitingAccept.push(suffix);
        else entry.staleAwaitingReroll.push(suffix);
      }
    } else {
      entry.missing.push(suffix);
    }
    // "Generated" (any output file) is a distinct axis from "accepted": it tells a
    // not-yet-accepted asset apart as awaiting-review vs never-generated. An asset with a job in
    // flight is neither — it is already handled, so it must not land in `notGenerated`.
    if (info.hasOutputFile) entry.generated++;
    countGenerateWork(entry, info, suffix);
  };

  for (const info of infos) {
    // Composition/stem leaves are materialized only on accept and never gate export (the export
    // gate keys on the underlying source assets), so they don't count toward the ratio — their
    // review need surfaces under "Needs review". An unresolved (null) address has no definition to
    // count. Generation assets AND `file` assets are counted (the latter surfaced separately so
    // they're visible/confirmable).
    if (
      info.assetKind === null ||
      info.assetKind === "composition" ||
      info.assetKind === "stem" ||
      info.assetKind === "animatic"
    )
      continue;

    const parsed = parseAddress(info.address);
    const base = formatAssetPathSuffix(parsed);
    accumulate(ensure(stageMap, parsed.stage), info, base);
  }

  // A stage whose shots are all undeveloped (pendingShot) has no address, so the
  // loop above created no entry for it. Seed one so its "N shots undeveloped" line still shows —
  // without this the whole stage vanishes from Progress.
  if (pendingShotsByStage) {
    for (const [stage, count] of Object.entries(pendingShotsByStage)) {
      if (count && count > 0) ensure(stageMap, stage);
    }
  }

  const results: ExportReadiness[] = [];
  for (const [label, entry] of stageMap) {
    results.push({
      label,
      total: entry.total,
      accepted: entry.accepted,
      missing: entry.missing,
      generated: entry.generated,
      notGenerated: entry.notGenerated,
      needsRegenerate: entry.needsRegenerate,
      inFlight: entry.inFlight,
      staleAwaitingReroll: entry.staleAwaitingReroll,
      staleAwaitingAccept: entry.staleAwaitingAccept,
      filesReady: entry.filesReady,
      filesMissing: entry.filesMissing,
      pendingShots: pendingShotsByStage?.[label as Stage] ?? 0,
      unacceptedCast: [],
      deliveryUpscalerMissing: false,
    });
  }
  // Report in pipeline order — the shared reference pool feeds animatic, which feeds video — so
  // the first unfinished line is the one to work on.
  const stageRank = (label: string) => {
    const rank = STAGE_ORDER.indexOf(label);
    return rank < 0 ? STAGE_ORDER.length : rank;
  };
  results.sort((a, b) => stageRank(a.label) - stageRank(b.label) || a.label.localeCompare(b.label));
  return results;
}
