import {
  formatAssetPath,
  type AssetStage,
  type ShotStage,
  formatTimelineAssetPath,
  formatPlateAssetPath,
} from "../address.js";
import type { AssetDefinition, Typography } from "../types/index.js";
import type { MediaKind } from "./builders.js";

export type ShotFunction = () => React.ReactElement;

/**
 * The stage canvas an adapter's format-derived inputs (width/height/fps) resolve against at
 * definition-build time.
 * `duration` (seconds) is the active shot's, present only inside a video shot discovery — a
 * timeline or reference build has no single duration — so a function default computing a frame
 * count from it must guard for undefined.
 */
export interface BuildFormat {
  size: { width: number; height: number };
  fps?: number;
  duration?: number;
  // How the stage typesets a document (`lang`, the declared Google Fonts), so an adapter that
  // renders its own HTML — `jsxImage` — resolves the same faces the compositions do. Absent
  // outside a stage that declares one (a delivery upscale).
  typography?: Typography;
}

interface ShotContext {
  mode: "discovery" | "render";
  stage: ShotStage;
  shotId: string;
  assets: Map<string, AssetDefinition>;
  // Each asset's declared output kind, taken from its adapter. An AssetDefinition does not carry
  // one (a comfy definition names only its workflow), so `shot`'s kind check reads this instead.
  assetKinds: Map<string, MediaKind>;
  resolvedFiles: Map<string, string>;
  absolutePaths: Map<string, string>;
  format?: BuildFormat;
}

export interface TimelineContext {
  mode: "discovery" | "render";
  stage: ShotStage;
  assets: Map<string, AssetDefinition>;
  resolvedFiles: Map<string, string>;
  absolutePaths: Map<string, string>;
  format?: BuildFormat;
}

// The reference stage has no shot/timeline axis — assets registered here become a flat
// named pool addressed as `reference:<name>`. Only a discovery pass exists (reference assets
// are generated by backends and resolved by file path, never re-rendered inside a closure).
//
// Its canvas is per asset rather than one for the stage: the shape is the roster's
// (`deriveReferenceSize`). `format` therefore takes the name being registered, which `asset()`
// publishes in `activeAssetName` for the length of one `createDefinition` call.
export interface ReferenceContext {
  assets: Map<string, AssetDefinition>;
  format: (assetName?: string) => BuildFormat;
  activeAssetName?: string;
}

// The animatic's `plates` callback, running to collect its pool. A flat pool like the reference
// stage's, but keyed by setup id and addressed `animatic:plate.<id>`. Discovery only: nothing re-runs
// it in render mode.
export interface PlatePoolContext {
  assets: Map<string, AssetDefinition>;
  format?: BuildFormat;
}

// A patch script's build, running to collect the steps of its chain. Like the reference stage it is
// a flat named pool with no shot/timeline axis, but it carries the stage and source variant its
// addresses are formed from, and a `format` so a step resolves format-derived inputs against the
// same canvas a stage asset would.
export interface PatchDiscoveryContext {
  assets: Map<string, AssetDefinition>;
  stage: AssetStage;
  sourceVariantId: string;
  format?: BuildFormat;
}

const PLACEHOLDER_PREFIX = "__konte:";
const PLACEHOLDER_SUFFIX = "__";

export function seed(): string {
  return `${PLACEHOLDER_PREFIX}seed${PLACEHOLDER_SUFFIX}`;
}

let currentContext: ShotContext | null = null;
let currentTimelineContext: TimelineContext | null = null;
let currentReferenceContext: ReferenceContext | null = null;
let currentPatchContext: PatchDiscoveryContext | null = null;
let currentPlatePoolContext: PlatePoolContext | null = null;

export function getShotContext(): ShotContext | null {
  return currentContext;
}

export function getTimelineContext(): TimelineContext | null {
  return currentTimelineContext;
}

export function getReferenceContext(): ReferenceContext | null {
  return currentReferenceContext;
}

export function getPatchContext(): PatchDiscoveryContext | null {
  return currentPatchContext;
}

export function getPlatePoolContext(): PlatePoolContext | null {
  return currentPlatePoolContext;
}

// The active build canvas, read by adapters resolving format-derived inputs (width/height/fps)
// inside createDefinition. A shot discovery suppresses its surrounding timeline context, so the
// shot's format wins there; otherwise the timeline's. A patch build carries its own, so a
// correction lands on the same canvas as the take it corrects. The reference stage resolves one per
// asset. Undefined outside a discovery pass (e.g. a delivery upscale) — those inputs then fall back
// to their declared default.
export function getActiveFormat(): BuildFormat | undefined {
  return (
    currentContext?.format ??
    currentTimelineContext?.format ??
    currentPatchContext?.format ??
    currentPlatePoolContext?.format ??
    currentReferenceContext?.format(currentReferenceContext.activeAssetName)
  );
}

// How the active build sets type, read by an adapter that renders its own HTML (`jsxImage`) so its
// still resolves the same faces the compositions do. Follows `getActiveFormat`'s precedence.
export function getActiveTypography(): Typography | undefined {
  return (
    currentContext?.format?.typography ??
    currentTimelineContext?.format?.typography ??
    currentPatchContext?.format?.typography ??
    currentPlatePoolContext?.format?.typography ??
    currentReferenceContext?.format(currentReferenceContext.activeAssetName).typography
  );
}

export function makePlaceholder(stage: ShotStage, shotId: string, assetName: string): string {
  return `${PLACEHOLDER_PREFIX}${formatAssetPath(stage, shotId, assetName)}${PLACEHOLDER_SUFFIX}`;
}

export function makeTimelinePlaceholder(stage: ShotStage, assetName: string): string {
  return `${PLACEHOLDER_PREFIX}${formatTimelineAssetPath(stage, assetName)}${PLACEHOLDER_SUFFIX}`;
}

export function makePlatePlaceholder(id: string): string {
  return `${PLACEHOLDER_PREFIX}${formatPlateAssetPath(id)}${PLACEHOLDER_SUFFIX}`;
}

export function makeReferencePlaceholder(assetName: string): string {
  return `${PLACEHOLDER_PREFIX}reference:${assetName}${PLACEHOLDER_SUFFIX}`;
}

export function makePatchPlaceholder(
  stage: AssetStage,
  sourceVariantId: string,
  assetName: string,
): string {
  return `${PLACEHOLDER_PREFIX}${stage}:patch.${sourceVariantId}.${assetName}${PLACEHOLDER_SUFFIX}`;
}

// A placeholder for an already-formatted address, used where the address is known as a whole
// rather than assembled from its parts (a patch's source variant).
export function makeAddressPlaceholder(address: string): string {
  return `${PLACEHOLDER_PREFIX}${address}${PLACEHOLDER_SUFFIX}`;
}

export function parsePlaceholder(value: string): string | null {
  if (value.startsWith(PLACEHOLDER_PREFIX) && value.endsWith(PLACEHOLDER_SUFFIX)) {
    return value.slice(PLACEHOLDER_PREFIX.length, -PLACEHOLDER_SUFFIX.length);
  }
  return null;
}

const REACT_ELEMENT_TYPE = Symbol.for("react.element");
// Every stage that owns a consumable asset.
const ASSET_PATH = /^(?:animatic|video|reference):/;

// Deep-walk a discovery-mode shotFn output (React element tree) and collect every
// asset path it references via placeholders. This is the source of truth for a
// composition's dependencies: it captures both the shot's own asset() calls AND
// timeline assets pulled in via closure (which never appear in shot.assets).
export function collectPlaceholderRefs(node: unknown): string[] {
  const refs = new Set<string>();
  const seen = new Set<object>();

  const visit = (value: unknown): void => {
    if (value == null) return;
    if (typeof value === "string") {
      const path = parsePlaceholder(value);
      if (path && ASSET_PATH.test(path)) refs.add(path);
      return;
    }
    if (typeof value !== "object") return;
    if (seen.has(value)) return;
    seen.add(value);

    if (Array.isArray(value)) {
      for (const item of value) visit(item);
      return;
    }
    const el = value as { $$typeof?: symbol; props?: unknown };
    if (el.$$typeof === REACT_ELEMENT_TYPE) {
      visit(el.props);
      return;
    }
    for (const v of Object.values(value as Record<string, unknown>)) visit(v);
  };

  visit(node);
  return [...refs];
}

export interface DiscoveryResult {
  assets: Record<string, AssetDefinition>;
  assetKinds: Map<string, MediaKind>;
  element: React.ReactElement;
}

export interface TimelineDiscoveryResult {
  assets: Record<string, AssetDefinition>;
  result: unknown;
}

export function runTimelineInDiscoveryMode<T>(
  stage: ShotStage,
  fn: () => T,
  format?: BuildFormat,
): TimelineDiscoveryResult {
  const ctx: TimelineContext = {
    mode: "discovery",
    stage,
    assets: new Map(),
    resolvedFiles: new Map(),
    absolutePaths: new Map(),
    format,
  };

  // Save/restore rather than reset to null: a nested run (e.g. a test that starts a shot chain
  // inside an outer timeline discovery) must leave the outer context standing when it returns.
  const prev = currentTimelineContext;
  currentTimelineContext = ctx;
  try {
    const result = fn();
    const assets: Record<string, AssetDefinition> = {};
    for (const [name, def] of ctx.assets) {
      assets[name] = def;
    }
    return { assets, result };
  } finally {
    currentTimelineContext = prev;
  }
}

export function runTimelineInRenderMode<T>(
  stage: ShotStage,
  fn: () => T,
  resolvedFiles: Record<string, string>,
  absolutePaths?: Record<string, string>,
): T {
  const ctx: TimelineContext = {
    mode: "render",
    stage,
    assets: new Map(),
    resolvedFiles: new Map(Object.entries(resolvedFiles)),
    absolutePaths: new Map(Object.entries(absolutePaths ?? {})),
  };

  const prev = currentTimelineContext;
  currentTimelineContext = ctx;
  try {
    return fn();
  } finally {
    currentTimelineContext = prev;
  }
}

export function runInDiscoveryMode(
  stage: ShotStage,
  shotId: string,
  fn: ShotFunction,
  format?: BuildFormat,
): DiscoveryResult {
  const ctx: ShotContext = {
    mode: "discovery",
    stage,
    shotId,
    assets: new Map(),
    assetKinds: new Map(),
    resolvedFiles: new Map(),
    absolutePaths: new Map(),
    format,
  };

  // Suppress any surrounding timeline context for the duration: a shot build only ever declares
  // shot-local assets, and `asset()` prefers a live timeline context (adapter.ts), so a shot
  // discovery nested inside one (e.g. the test `shot()` helper) would otherwise leak the shot's
  // assets into the timeline. In the normal defineVideo path the timeline context is already
  // cleared by the time shots are discovered, so this is a no-op there.
  const prev = currentContext;
  const prevTimeline = currentTimelineContext;
  currentContext = ctx;
  currentTimelineContext = null;
  try {
    const element = fn();
    const assets: Record<string, AssetDefinition> = {};
    for (const [name, def] of ctx.assets) {
      assets[name] = def;
    }
    return { assets, assetKinds: ctx.assetKinds, element };
  } finally {
    currentContext = prev;
    currentTimelineContext = prevTimeline;
  }
}

export function runInPatchDiscoveryMode<T>(
  stage: AssetStage,
  sourceVariantId: string,
  fn: () => T,
  format?: BuildFormat,
): TimelineDiscoveryResult {
  const ctx: PatchDiscoveryContext = { assets: new Map(), stage, sourceVariantId, format };
  const prev = currentPatchContext;
  currentPatchContext = ctx;
  try {
    const result = fn();
    const assets: Record<string, AssetDefinition> = {};
    for (const [name, def] of ctx.assets) {
      assets[name] = def;
    }
    return { assets, result };
  } finally {
    currentPatchContext = prev;
  }
}

export function runInPlateDiscoveryMode<T>(
  fn: () => T,
  format?: BuildFormat,
): TimelineDiscoveryResult {
  const ctx: PlatePoolContext = { assets: new Map(), ...(format ? { format } : {}) };
  const prev = currentPlatePoolContext;
  currentPlatePoolContext = ctx;
  try {
    const result = fn();
    const assets: Record<string, AssetDefinition> = {};
    for (const [name, def] of ctx.assets) {
      assets[name] = def;
    }
    return { assets, result };
  } finally {
    currentPlatePoolContext = prev;
  }
}

export function runInReferenceDiscoveryMode<T>(
  fn: () => T,
  format: (assetName?: string) => BuildFormat,
): TimelineDiscoveryResult {
  const ctx: ReferenceContext = { assets: new Map(), format };
  const prev = currentReferenceContext;
  currentReferenceContext = ctx;
  try {
    const result = fn();
    const assets: Record<string, AssetDefinition> = {};
    for (const [name, def] of ctx.assets) {
      assets[name] = def;
    }
    return { assets, result };
  } finally {
    currentReferenceContext = prev;
  }
}

export function runInRenderMode(
  stage: ShotStage,
  shotId: string,
  fn: ShotFunction,
  resolvedFiles: Record<string, string>,
  absolutePaths?: Record<string, string>,
): React.ReactElement {
  const ctx: ShotContext = {
    mode: "render",
    stage,
    shotId,
    assets: new Map(),
    assetKinds: new Map(),
    resolvedFiles: new Map(Object.entries(resolvedFiles)),
    absolutePaths: new Map(Object.entries(absolutePaths ?? {})),
  };

  const prev = currentContext;
  const prevTimeline = currentTimelineContext;
  currentContext = ctx;
  currentTimelineContext = null;
  try {
    return fn();
  } finally {
    currentContext = prev;
    currentTimelineContext = prevTimeline;
  }
}
